# Generated by Django 2.2.28 on 2024-01-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20240128_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='likes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(),
        ),
    ]
